### ISSUE TITLE
Bypass of steps 

### ISSUE THREAD

**Issue by onos1** [mcfarhat/actifit#1]
I don't know the steps are gotten, but I noted that steps increased by just shaking my phone

**Comment by mcfarhat** [comment]
Thanks Onos1!
The counter is not only a step counter, more of a move/activity counter.
It is made quite sensitive to capture for the different activities performed by the user.
Yes shaking the phone would lead to an increase in the count, but you will not be benefiting health-wise, which defies the purpose of the app. The app aims to promote health and fitness, I would be sorry for users who can't relate to how important having a healthy lifestyle and would just shake the phone.
We are though constantly improving the app and coming up with ways to prevent abuse as well.
