### ISSUE TITLE
Suggestion on how to improve step counting

### ISSUE THREAD

**Issue by Anyadan** [mcfarhat/actifit#5]
Hello sir. I just got to use your app yesterday and I must say it's very nice. My tip on how to further improve the walking/running step counter is to integrate the app to work with the phone's gps(which would require permissions). This way when someone is doing a walking/running activity, steps won't be achieved or counted unless the app detects a change in movement through the GPS sensor. I hope this suggestion would be of help.

**Comment by mcfarhat** [comment]
Thank you, we plan on adding GPS integration, but also the app targets people who use indoor training, treadmill, and other activities that do not require GPS movement.
