### ISSUE TITLE
Changes to Donate to Charity Settings do not Save

### ISSUE THREAD

**Issue by thewizardstudio** [mcfarhat/actifit#8]
#### Expected Behavior

Changes to the Donate to Charity sections of the Settings menu is saved.  Available Charities dropdown has available selections.

#### Actual Behavior

Changes to the Donate to Charity sections of the Settings menu are not saved.  The Available Charities dropdown has no selectable options.

#### How to Reproduce
1. Install Actifit for Android
2. Launch Actifit
3. Tap Settings
4. Tap Checkbox for Donate Rewards to Charity
5. Tap Save Settings
6. Tap Back button
7. Tap Settings

#### Test Environment
- OS: Android 8.1.0
- App: 0.3beta

#### Recording Of The Bug
https://youtu.be/OJsAlXDiLFg

**Comment by mcfarhat** [comment]
@thewizardstudio it is normal that they do not save at the moment as the list is empty. Once filled the behaviour will change
